[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.7"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"

  # Commit that is compatible with client-go v4.0.0.
  # Thanks to https://github.com/kubernetes/apiextensions-apiserver/issues/3#issuecomment-318871483
  revision = "be41f5093e2b05c7a0befe35b04b715eb325ab43"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"