apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis-operator
  name: redis-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-operator
    spec:
      containers:
      - image: redis-operator:latest
        imagePullPolicy: Never
        name: redis-operator
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi