apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ include "redis-operator.name" . }}
    chart: {{ include "redis-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: redis-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - operator.joelws.com
  resources:
  - redises
  - redises/finalizers
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - list
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - '*'