apiVersion: operator.joelws.com/v1
kind: Redis
metadata:
  name: redis-default
spec:
  sentinels:
    replicas: {{ .Values.redis.sentinels.replicas }}
    quorum: {{ .Values.redis.sentinels.quorum }}
  slaves:
    replicas: {{ .Values.redis.slaves.replicas }}